# Generated by Django 3.1.7 on 2021-03-03 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Zone',
            new_name='Zones',
        ),
    ]
