# Generated by Django 3.1.7 on 2021-03-25 17:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0001_initial'),
        ('sensor', '0002_auto_20210310_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=None, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='zone',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='zone.zone'),
        ),
    ]
