# Generated by Django 3.1.7 on 2021-03-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0003_auto_20210325_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='sensorLabel',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
